# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CounterQuoteAgentApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
    pod 'TwilioVideo', '~> 1.3.3'
    pod 'IQKeyboardManagerSwift', '4.0.10'
  # Pods for CounterQuoteAgentApp

end
