# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CounterQuoteAgentApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
    pod 'TwilioVideo', '~> 1.3.3'
    pod 'IQKeyboardManagerSwift', '~> 5.0.6'
    pod 'Firebase/Database', '~> 4.1.1'
    pod 'Firebase/Auth', '~> 4.1.1'
    pod 'Firebase/Storage'
  # Pods for CounterQuoteAgentApp

end
