# Uncomment the next line to define a global platform for your project
platform :ios, ’10.0’

target 'SyneScanner' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

    pod 'Alamofire', '~> 4.5'
    pod 'IQKeyboardManagerSwift'
    pod 'SVProgressHUD'
    pod 'DKImagePickerController'
    pod 'UICircularProgressRing'
    pod 'CardIO'
    pod 'SwiftGifOrigin', '~> 1.6.1'
    pod 'TwilioVideo', '~> 1.3.3'
    
    pod 'Firebase/Database'
    pod 'Firebase/Auth'
    pod 'Firebase/Storage'
target 'SyneScannerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SyneScannerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
