# Uncomment the next line to define a global platform for your project
platform :ios, ’10.0’

target 'SyneScanner' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

    pod 'Alamofire', '~> 4.5'
    pod 'IQKeyboardManagerSwift', '~> 5.0.6'
    pod 'SVProgressHUD', '~> 2.2'
    pod 'DKImagePickerController', '~> 3.8.1'
    pod 'UICircularProgressRing', '~> 1.7.2'
    pod 'CardIO', '~> 5.4.1'
    pod 'SwiftGifOrigin', '~> 1.6.1'
    pod 'TwilioVideo', '~> 1.3.3'
    
    pod 'Firebase/Database'
    pod 'Firebase/Auth'
    pod 'Firebase/Storage'
target 'SyneScannerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SyneScannerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
